plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.4'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'org.flywaydb.flyway' version '10.20.0'
	id 'pl.allegro.tech.build.axion-release' version '1.18.14'
}

group = 'com.henriquenascimento'
version = "0.0.2"

apply from: 'versioning.gradle'
scmVersion {
	tag { prefix = '' }
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

ext {
	springCloudVersion = '2023.0.2'
	springCloudAWSVersion = '3.1.1'
	mapstructVersion = "1.6.0"
	flywayVersion = '10.20.0'
	ojdbcVersion = '23.5.0.24.07'
	hibernateVersion = '6.4.10.Final'
	springDocVersion = '2.6.0'
	lombokVersion = '1.18.34'
}

dependencies {
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.boot:spring-boot-starter-data-jpa"
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-aop'

	implementation "org.mapstruct:mapstruct:${mapstructVersion}"

	// DATABASES
	implementation "org.hibernate.orm:hibernate-core:${hibernateVersion}"
	implementation "org.hibernate.orm:hibernate-envers:${hibernateVersion}"
	implementation "com.oracle.database.jdbc:ojdbc11:${ojdbcVersion}"

	implementation "org.flywaydb:flyway-core:${flywayVersion}"
	runtimeOnly("org.flywaydb:flyway-database-oracle:${flywayVersion}")


	testImplementation "org.springframework.boot:spring-boot-starter-test"

	compileOnly "org.projectlombok:lombok:${lombokVersion}"

	testCompileOnly "org.projectlombok:lombok:${lombokVersion}"

	testRuntimeOnly "org.junit.platform:junit-platform-launcher"

	annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

	testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
	testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springDocVersion}"
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'
	implementation 'software.amazon.awssdk:sts'

	implementation 'software.amazon.awssdk:sts:2.29.9'
	implementation 'software.amazon.awssdk:s3:2.29.9'

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		mavenBom "io.awspring.cloud:spring-cloud-aws-dependencies:${springCloudAWSVersion}"

	}
}

tasks.named('test') {
	useJUnitPlatform()
}
