INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT)
    VALUES ('Laptop', 'A high-performance laptop.', 'AVAILABLE', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Smartphone', 'A flagship smartphone.', 'OUT_OF_STOCK', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Headphones', 'Noise-cancelling headphones.', 'DISCONTINUED', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Smartwatch', 'A smartwatch with health tracking features.', 'PENDING', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Tablet', 'A tablet for media consumption.', 'PRE_ORDER', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Camera', 'A DSLR camera with high resolution.', 'IN_TRANSIT', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Monitor', 'A 4K Ultra HD monitor.', 'BACKORDERED', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Printer', 'A wireless color printer.', 'AVAILABLE', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Router', 'A high-speed wireless router.', 'OUT_OF_STOCK', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS, CREATED_AT) VALUES
    ('Keyboard', 'A mechanical keyboard with RGB lighting.', 'AVAILABLE', CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
