INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Laptop', 'A high-performance laptop.', 'AVAILABLE');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Smartphone', 'A flagship smartphone.', 'OUT_OF_STOCK');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Headphones', 'Noise-cancelling headphones.', 'DISCONTINUED');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Smartwatch', 'A smartwatch with health tracking features.', 'PENDING');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Tablet', 'A tablet for media consumption.', 'PRE_ORDER');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Camera', 'A DSLR camera with high resolution.', 'IN_TRANSIT');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Monitor', 'A 4K Ultra HD monitor.', 'BACKORDERED');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Printer', 'A wireless color printer.', 'AVAILABLE');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Router', 'A high-speed wireless router.', 'OUT_OF_STOCK');
INSERT INTO PRODUCT (NAME, DESCRIPTION, STATUS) VALUES ('Keyboard', 'A mechanical keyboard with RGB lighting.', 'AVAILABLE');
