spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/DEV_DEMO_APP_SPRING
    username: dev_demo
    password: dev_demo

cloud:
  aws:
    s3:
      bucket-name: demo-app-bucket-90
      acl_default: private

management:
  info:
    java.enabled: true
    os.enabled: true
    process.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
