version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: demo-application-spring-oracle
    environment:
      ORACLE_PASSWORD: root
      ORACLE_DATABASE: DEMO_APP_SPRING
      APP_USER: DEMO_SCHEMA
      APP_USER_PASSWORD: DEMO_SCHEMA
      ORACLE_CHARACTERSET: AL32UTF8
    ports:    
      - 1521:1521
